title = "ALmiraj"
description = "TeXify3 - A LaTeX-style hugo theme with the gruvbox color scheme for personal blogging"
footnote = """
Made with <a href="https://gohugo.io" target="_blank">
<img src="/images/icons/hugo.svg" alt="Hugo" width="45px" height="12px"class="hugo-svg">
</a>Theme <a class=link href=https://github.com/michaelneuper/hugo-texify3 target=_blank rel=noopener>UnTeXify3</a>
"""
keywords = ["عزالدين", "linux", "blog", "productivity"]
customCSS = ["css/styles.css"]
customJS = []
dateFormat = "2 January 2006"
emphasisWithDots = true
since = "2023"
toc = true
showWordCount = true
showReadingTime = true
rootFontSize = "100%"
numberedSubtitles = true
enableInlineShortcodes = true

defaultContentLanguage = 'ar'
# defaultContentLanguageInSubdir = true
[languages]
  [languages.ar]
    # contentDir = 'content/de'
    disabled = false
    languageCode = 'ar'
    languageDirection = 'rtl'
    languageName = 'arabic'
    title = 'المعراج'
    weight = 1
  
