baseURL = ""
disqusShortname = ""
enableGitInfo = true
enableRobotsTXT = true
hasCJKLanguage = true
languageCode = "en"
paginate = 5
rssLimit = 10
theme = "hugo-untexify3"
title = "Almiraj"

[author]
name = "Ezz el-dean"
email = "ezznabil@almiraj.xyz"

[taxonomies]
tags = "tags"
categories = "categories"

[params]
title="UnTeXify3"
description = "UnTeXify3 - A hugo theme with the gruvbox color scheme for personal blogging"
footnote = """
Powered by  <a class=link href=https://gohugo.io target=_blank rel=noopener>Hugo</a> | 
Theme <a class=link href=https://github.com/AnonMiraj/hugo-UNtexify3 target=_blank rel=noopener>TeXify3</a>
"""
customCSS = []
customJS = []
dateFormat = "2 January 2006"
emphasisWithDots = true
toc = true
rootFontSize = "105%"
enableDuckDuckGoSearchBox = false
numberedSubtitles = true
